export const LIMIT = 5

//注册
export const USER_UNLOAD = "USER_UNLOAD"
export const USER_REGIST_UNLOAD = "USER_REGIST_UNLOAD"
export const USER_REGIST_FIELD = "USER_REGIST_FIELD"
export const USER_REGIST_RESULT = "USER_REGIST_RESULT"

//登录
export const USER_LOGIN_UNLOAD = "USER_LOGIN_UNLOAD"
export const USER_LOGIN_FIELD = "USER_LOGIN_FIELD"
export const USER_LOGIN_RESULT = "USER_LOGIN_RESULT"

// 设置
export const SETTING_UNLOAD = "SETTING_UNLOAD"
export const SETTING_FIELD = "SETTING_FIELD"
export const SETTING_RESULT = "SETTING_RESULT"

export const USER_LOGOUT = "USER_LOGOUT"

//用户中心
export const PROFILE_GET_RESULT = "PROFILE_GET_RESULT"
export const PROFILE_FOLLOW_RESULT = "PROFILE_FOLLOW_RESULT"

// 文章列表
export const ARTICLES_AUTHOR_RESULT = "ARTICLES_AUTHOR_RESULT"

//单个文章
export const ARTICLE_UNLOAD = "ARTICLE_UNLOAD"
export const ARTICLE_CREATE_FIELD = "ARTICLE_CREATE_FIELD"
export const ARTICLE_ADD_TAG = "ARTICLE_ADD_TAG"
export const ARTICLE_REMOVE_TAG = "ARTICLE_REMOVE_TAG"
export const ARTICLE_CREATE_RESULT = "ARTICLE_CREATE_RESULT"
export const ARTICLE_GET_RESULT = "ARTICLE_GET_RESULT"
export const ARTICLE_UPDATE_RESULT = "ARTICLE_UPDATE_RESULT"
export const ARTICLE_DELETE_RESULT = "ARTICLE_DELETE_RESULT"

export const ARTICLE_FAVORITE_RESULT = "ARTICLE_FAVORITE_RESULT"

// 评论
export const COMMENT_UNLOAD = "COMMENT_UNLOAD"
export const COMMENT_CREATE_FIELD = "COMMENT_CREATE_FIELD"
export const COMMENTS_GET_RESULT = "COMMENTS_GET_RESULT"
export const COMMENT_CREATE_RESULT = "COMMENT_CREATE_RESULT"
export const COMMENT_DELETE_RESULT = "COMMENT_DELETE_RESULT"

//首页
export const TAGS_GET_RESULT = "TAGS_GET_RESULT"
export const HOME_ARTICLES_RESULT = "HOME_ARTICLES_RESULT"
export const HOME_PAGE_SYNC = "HOME_PAGE_SYNC"
export const HOME_TAB_SYNC = "HOME_TAB_SYNC"
export const HOME_TAG_SYNC = "HOME_TAG_SYNC"